// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TesteCT02Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testeCT02() {
    driver.get("http://localhost:8080/vendas/");
    driver.manage().window().setSize(new Dimension(720, 900));
    driver.findElement(By.cssSelector("html")).click();
    {
      WebElement element = driver.findElement(By.linkText("Cadastros"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-state-hover > .ui-menuitem-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("j_idt14:j_idt17")).click();
    driver.findElement(By.cssSelector("#frmCadastro\\3Aj_idt37 > .ui-button-text")).click();
    driver.findElement(By.id("frmPesquisa:codigo")).click();
    driver.findElement(By.id("frmPesquisa:codigo")).sendKeys("9999");
    driver.findElement(By.cssSelector("#frmPesquisa\\3Aj_idt34 > .ui-button-text")).click();
  }
}
